
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        # Config base de données
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider  # Utilisateurs enregistrés dans la base de données
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
                default_target_path: app_admin
            logout:
                path: app_logout
                target: home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile, roles: ROLE_USER }

